# Generated by Django 4.2.5 on 2023-09-29 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО клиента/Наименование компании')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerIndividual',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_project.customer')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Страхователь Физ.Лицо',
            },
            bases=('my_project.customer',),
        ),
        migrations.CreateModel(
            name='CustomerLegalEntity',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_project.customer')),
                ('inn', models.CharField(max_length=25, verbose_name='ИНН')),
                ('okpo', models.CharField(blank=True, help_text='Общегосударственный классификатор предприятий и организаций', max_length=25, null=True, verbose_name='Код ОКПО')),
                ('registration_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регистрационный номер')),
                ('fax', models.CharField(blank=True, max_length=255, null=True, verbose_name='Факс')),
                ('ceo', models.ForeignKey(help_text='Руководитель компании', on_delete=django.db.models.deletion.RESTRICT, related_name='legal_boss', to='my_project.customerindividual', verbose_name='Руководитель')),
            ],
            bases=('my_project.customer',),
        ),
    ]
